LOGIN_URL = "https://www.facebook.com"
LOGIN_PAGE_HEADER = "xpath://*[contains(@class,'fb_logo')]"
LOGIN_PAGE_USERNAME = "id:email"
LOGIN_PAGE_PASSWORD = "id:pass"
LOGIN_PAGE_LOGIN_BTN = "name:login"
LOGIN_PAGE_DASHBOARD = "xpath://*[contains(@class,'fb_logo')]"